name: Deploy React App to GitHub Pages

on:
  push:
    branches:
      - main
      - master
  pull_request:
    types: [ opened, synchronize, reopened ]
    branches:
      - main
      - master
  workflow_dispatch:

concurrency: preview-${{ github.ref }}

jobs:
  build:
    name: Build React App
    runs-on: ubuntu-latest
    permissions:
      contents: read # to download the repository
      pages: write # to upload the build artifact
      id-token: write # to verify the deployment originates from an appropriate source
    env:
      REACT_APP_EMAIL: ${{ vars.REACT_APP_EMAIL }}

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: npm

      - name: Install dependencies
        run: npm ci

      - name: Build React app
        run: npm run build

      - name: Upload Build Artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: build

  deploy:
    name: Deploy to GitHub Pages
    needs: build
    if: github.event_name == 'push'

    # Grant GITHUB_TOKEN the permissions required to make a Pages deployment
    permissions:
      pages: write # to deploy to Pages
      id-token: write # to verify the deployment originates from an appropriate source

    # Deploy to the github-pages environment
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    runs-on: ubuntu-latest
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4

  deploy-preview:
    name: "Deploy Preview for PR #${{github.event.pull_request.number}}"
    if: github.event_name == 'pull_request' # Only run for pull requests
    runs-on: ubuntu-latest
    # Grant GITHUB_TOKEN the permissions required to make a Pages deployment
    permissions:
      pages: write # to deploy to Pages
      pull-requests: write
      contents: write
      id-token: write
    env:
      REACT_APP_EMAIL: ${{ vars.REACT_APP_EMAIL }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: npm

      - name: Install and Build
        run: |
          npm ci
          npm run build

      - name: Deploy preview
        uses: rossjrw/pr-preview-action@v1
        with:
          source-dir: ./build/
          action: 'auto'